version: "3.8"

services:
  # PostgreSQL for production
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: prismeet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # Django Backend (prod)
  backend:
    build:
      context: ./docker/backend
    env_file:
      - ./.env.prod
    expose:
      - "8000"
    working_dir: /app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  # Next.js Frontend (prod)
  frontend:
    build:
      context: ./docker/frontend
    env_file:
      - ./.env.prod
    expose:
      - "3000"
    working_dir: /app
    command: bash -lc "npm run build && npm run start"
    depends_on:
      - backend

  # Nginx as reverse proxy
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
